### ISSUE TITLE
Great script, be good when unmasko it shows a success!

### ISSUE THREAD

**Issue by shaunrainer** [Danny-mcc/jquery-mask-o#3]
So recently I used this script for dynamically saving one of my forms. on successfully saving it would be cool if you could show a successful (Thumbs Up icon) before unmasko'ing or error (Sad Face icon)

**Comment by Danny-mcc** [comment]
I've added support for callbacks. So you can now add your code to display a thumbs up/down here.

```
$(form).masko({}, function(){
    console.log(':-)');
});


$(form).unmasko(function(){
    // Show thumbs up!
});
```

Take a look at the source code on the example page http://danny-mcc.github.io/jquery-mask-o/

**Comment by shaunrainer** [comment]
Fantastic! Great work have a wonderful Christmas!
